name: WildFly Build

on:
  pull_request:

jobs:
  quick-build:
    name: WildFly Build -Dquickly
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Clear any possible SNAPSHOT dependencies in the local maven repository
        run: |
          LOCAL_REPO="$HOME/.m2/repository"
          echo "Cleaning SNAPSHOTS from $LOCAL_REPO"
          if [ -d "$LOCAL_REPO" ]; then find "$LOCAL_REPO" -name "*SNAPSHOT*" | xargs -I {} rm -rfv "{}"; fi
        shell: bash
      - name: Build with Maven Java 11 -Dquickly
        run: mvn -U -B -Dquickly