name: Cloud Tests Trigger
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".mvn/**"
      - "docs/**"
      - ".github/workflows/build-manual.yml"
      - ".github/workflows/shared-wildfly-build.yml"
      - '.gitattributes'
      - '.gitignore'
      - '.gitleaks.toml'
      - 'build.bat'
      - 'build.sh'
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "integration-tests.bat"
      - "integration-tests.sh"
      - "LICENSE.txt"
      - "mvnw"
      - "mvnw.cmd"
      - "README.md"
      - "SECURITY.md"
      - "**/README.md"
      - "**/README.adoc"

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref || github.run_id }}'
  cancel-in-progress: true

permissions: {}
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Get pull request number
      run: |
        event_name="${{ github.event_name }}"
        echo "PR_NUMBER=${{ github.event.number }}" >> .job-env
        echo "GITHUB_SHA_FOR_PR=${{ github.sha }}" >> .job-env
        echo "GITHUB_EVENT_PULL_REQUEST_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> .job-env
        cat .job-env
    - uses: actions/upload-artifact@v6
      with:
        name: .job-env
        path: .job-env
        include-hidden-files: true
